apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service
  namespace: feedback-service
  labels:
    app: feedback-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: feedback-service
  template:
    metadata:
      labels:
        app: feedback-service
    spec:
      containers:
      - name: feedback-service
        image: feedback-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: feedback-service-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: feedback-service-config
              key: REDIS_URL
        - name: ELASTICSEARCH_URL
          valueFrom:
            configMapKeyRef:
              name: feedback-service-config
              key: ELASTICSEARCH_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: feedback-service-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: feedback-service-secrets
              key: SECRET_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
