apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: content-enrichment-hpa
  namespace: content-enrichment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: content-enrichment-service
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: content_enrichment_active_requests
      target:
        type: AverageValue
        averageValue: "50"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: content-enrichment-service-monitor
  namespace: content-enrichment
  labels:
    app: content-enrichment-service
spec:
  selector:
    matchLabels:
      app: content-enrichment-service
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
