apiVersion: v1
kind: Namespace
metadata:
  name: content-enrichment
  labels:
    name: content-enrichment
    app: content-enrichment-service
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: content-enrichment-quota
  namespace: content-enrichment
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: content-enrichment-limits
  namespace: content-enrichment
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Container
