apiVersion: v1
kind: ServiceAccount
metadata:
  name: content-enrichment-service-account
  namespace: content-enrichment
  labels:
    app: content-enrichment-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: content-enrichment-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: content-enrichment-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: content-enrichment-role
subjects:
- kind: ServiceAccount
  name: content-enrichment-service-account
  namespace: content-enrichment
---
apiVersion: v1
kind: Role
metadata:
  namespace: content-enrichment
  name: content-enrichment-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: content-enrichment-role-binding
  namespace: content-enrichment
subjects:
- kind: ServiceAccount
  name: content-enrichment-service-account
  namespace: content-enrichment
roleRef:
  kind: Role
  name: content-enrichment-role
  apiGroup: rbac.authorization.k8s.io
