global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "feedback_rules.yml"

scrape_configs:
  - job_name: 'feedback-service'
    static_configs:
      - targets: ['feedback-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
