global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'content-enrichment-service'
    static_configs:
      - targets: ['content-enrichment-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    # Note: You would need to install postgres_exporter for this to work

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    # Note: You would need to install redis_exporter for this to work

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    # Note: You would need to install mlflow_exporter for this to work
