global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "storage_rules.yml"

scrape_configs:
  - job_name: 'storage-service'
    static_configs:
      - targets: ['storage-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 10s

  - job_name: 'timescale'
    static_configs:
      - targets: ['timescale-exporter:9187']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
