# Secret for sensitive configuration
# Note: In production, use external secret management like Google Secret Manager
apiVersion: v1
kind: Secret
metadata:
  name: foundations-guards-secrets
  namespace: foundations-guards
  labels:
    app: foundations-guards-service
    component: secrets
type: Opaque
stringData:
  # JWT Secret Key (should be base64 encoded in production)
  SECRET_KEY: "your-super-secret-jwt-key-change-in-production"
  
  # Firebase Credentials JSON (should be actual service account JSON)
  FIREBASE_CREDENTIALS_JSON: |
    {
      "type": "service_account",
      "project_id": "your-firebase-project-id",
      "private_key_id": "key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk@your-project.iam.gserviceaccount.com",
      "client_id": "client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk%40your-project.iam.gserviceaccount.com"
    }
  
  # Redis URL with authentication
  REDIS_URL: "redis://:password@redis-service:6379/0"
  
  # Firebase Project ID
  FIREBASE_PROJECT_ID: "your-firebase-project-id"
  
  # GCP Project Configuration
  GCP_PROJECT_ID: "your-gcp-project-id"
  GCP_REGION: "us-central1"

---
# External Secret Operator configuration (if using)
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: gcpsm-secret-store
#   namespace: foundations-guards
# spec:
#   provider:
#     gcpsm:
#       projectId: "your-gcp-project-id"
#       auth:
#         workloadIdentity:
#           clusterLocation: us-central1
#           clusterName: your-cluster
#           serviceAccountRef:
#             name: foundations-guards-sa

---
# External Secret for Firebase credentials (if using External Secrets Operator)
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: foundations-guards-firebase-secret
#   namespace: foundations-guards
# spec:
#   refreshInterval: 15s
#   secretStoreRef:
#     name: gcpsm-secret-store
#     kind: SecretStore
#   target:
#     name: foundations-guards-firebase-secret
#     creationPolicy: Owner
#   data:
#   - secretKey: FIREBASE_CREDENTIALS_JSON
#     remoteRef:
#       key: foundations-guards-firebase-credentials
