apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking-service
  labels:
    app: ranking-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ranking-service
  template:
    metadata:
      labels:
        app: ranking-service
    spec:
      containers:
      - name: ranking-service
        image: ranking-service:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: metrics
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: WORKERS
          value: "1"
        - name: LOG_LEVEL
          value: "info"
        - name: PROMETHEUS_PORT
          value: "8001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: models
          mountPath: /app/models
      volumes:
      - name: models
        configMap:
          name: ranking-models
---
apiVersion: v1
kind: Service
metadata:
  name: ranking-service
spec:
  selector:
    app: ranking-service
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 8001
    targetPort: 8001
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ranking-models
data:
  model_v3.pkl: |
    # Placeholder for model file
    # In production, this would be a binary model file
