global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "personalization_rules.yml"

scrape_configs:
  - job_name: 'personalization-service'
    static_configs:
      - targets: ['personalization-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
